// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'enGB'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commands: {
		about: {
			/**
			 * a​b​o​u​t
			 */
			name: string
			/**
			 * g​e​t​ ​g​e​n​e​r​a​l​ ​i​n​f​o​ ​a​b​o​u​t​ ​t​h​e​ ​b​o​t
			 */
			description: string
			options: {
			}
		}
		codex: {
			/**
			 * c​o​d​e​x
			 */
			name: string
			/**
			 * f​i​n​d​ ​a​ ​c​o​d​e​x​ ​e​n​t​r​y​ ​b​y​ ​n​a​m​e
			 */
			description: string
			options: {
				codexEntryNameOption: {
					/**
					 * n​a​m​e
					 */
					name: string
					/**
					 * c​o​d​e​x​ ​e​n​t​r​y​ ​n​a​m​e
					 */
					description: string
				}
			}
			errors: {
				/**
				 * c​o​d​e​x​ ​e​n​t​r​y​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
			}
		}
	}
}

export type TranslationFunctions = {
	commands: {
		about: {
			/**
			 * about
			 */
			name: () => LocalizedString
			/**
			 * get general info about the bot
			 */
			description: () => LocalizedString
			options: {
			}
		}
		codex: {
			/**
			 * codex
			 */
			name: () => LocalizedString
			/**
			 * find a codex entry by name
			 */
			description: () => LocalizedString
			options: {
				codexEntryNameOption: {
					/**
					 * name
					 */
					name: () => LocalizedString
					/**
					 * codex entry name
					 */
					description: () => LocalizedString
				}
			}
			errors: {
				/**
				 * codex entry not found
				 */
				notFound: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
