alter table subscriptions add column auto_delete boolean not null default false;

create table notifications (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT now(),
  channel_id VARCHAR(255) not null,
  message_id VARCHAR(255) not null,
  time timestamp not null,
  flagged_for_deletion boolean not null DEFAULT false,
  deleted boolean not null DEFAULT false
);
