create table events (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT now(),
  type VARCHAR(255) not null,
  name VARCHAR(255) not null,
  location VARCHAR(255) not null,
  time timestamp not null
);

create table subscriptions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT now(),
  channel_id VARCHAR(255) not null,
  guild_id VARCHAR(255) not null,
  worldBoss boolean not null DEFAULT true,
  helltide boolean not null DEFAULT true,
  zoneEvent boolean not null DEFAULT false,
  role VARCHAR(255),
  boss_role VARCHAR(255),
  helltide_role VARCHAR(255),
  event_role VARCHAR(255)
);
