create table guilds (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT now(),
  guild_id VARCHAR(255) not null UNIQUE,
  locale VARCHAR(8) not null default 'en-US'
);

alter table notifications add column locale VARCHAR(8) not null default 'en-US';
